IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.SP_GET_PROMOTION_STATUS_DATA'))
	DROP PROCEDURE [dbo].[SP_GET_PROMOTION_STATUS_DATA]
GO

CREATE PROCEDURE [dbo].[SP_GET_PROMOTION_STATUS_DATA]
	@BatchID DECIMAL = 182599,
	@Location DECIMAL = 924,
	@LoadWeek DECIMAL = 9,
	@LoadBatchID DECIMAL = 122176113,
	@RunIdentifier nvarchar(40)
AS
BEGIN
	SELECT DISTINCT
		@RunIdentifier AS 'RUN_IDENTIFIER',
		h.[BATCH_ID],
		h.[LOCATION],
		h.[LOCATION] AS 'STORE',
		h.[LOAD_WEEK],
		h.[LOAD_BATCH_ID],
		'P' AS 'PROCESSING_STATUS',
		GETDATE() AS 'COPY_START_TIME'
	FROM [dbo].[CO_PRM_DAT_HDR] h
	WHERE h.[BATCH_ID] = @BatchID and h.[LOCATION] = @Location and h.[LOAD_BATCH_ID] = @LoadBatchID
END
