IF OBJECT_ID (N'POS_PRM_HEAD', N'U') IS NOT NULL
BEGIN
  DROP TABLE [POS_PRM_HEAD] ;
END

CREATE TABLE [dbo].[POS_PRM_HEAD](
	[BATCH_ID] DECIMAL NULL,
	[LOCATION] DECIMAL NULL,
	[ARCHIVO] [nvarchar](255) NULL,
	[LOAD_DATE] [datetime2] NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL,
	[WM_PRM_STATUS] [nvarchar](1) NULL,
	[WM_TARGET_PRM] [nvarchar](255) NULL,
	[CLOUD_PRM_STATUS] [nvarchar](1) NULL,
	[CLOUD_TARGET_PRM] [nvarchar](255) NULL
) ON [PRIMARY]
GO


IF OBJECT_ID (N'FEM_POS_MODS_PRM_STG', N'U') IS NOT NULL
BEGIN
  DROP TABLE [FEM_POS_MODS_PRM_STG] ;
END

CREATE TABLE [dbo].[FEM_POS_MODS_PRM_STG](
	[STORE] DECIMAL(10) NULL,
	[UPDATE_TYPE] DECIMAL NULL,
	[START_DATE] [datetime2] NULL,
	[END_DATE] [datetime2] NULL,
	[TIME] [datetime2] NULL,
	[END_TIME] [datetime2] NULL,
	[TRAN_TYPE] DECIMAL(2) NULL,
	[ITEM] [nvarchar](25) NULL,
	[ITEM_NUMBER_TYPE] [nvarchar](6) NULL,
	[FORMAT_ID] [nvarchar](1) NULL,
	[PREFIX] DECIMAL(2) NULL,
	[REF_ITEM] [nvarchar](25) NULL,
	[REF_ITEM_NUMBER_TYPE] [nvarchar](6) NULL,
	[REF_FORMAT_ID] [nvarchar](1) NULL,
	[REF_PREFIX] DECIMAL(2) NULL,
	[ITEM_SHORT_DESC] [nvarchar](20) NULL,
	[ITEM_LONG_DESC] [nvarchar](100) NULL,
	[DEPT] DECIMAL(4) NULL,
	[CLASS] DECIMAL(4) NULL,
	[SUBCLASS] DECIMAL(4) NULL,
	[NEW_PRICE] DECIMAL(20,4) NULL,
	[NEW_SELLING_UOM] [nvarchar](4) NULL,
	[NEW_MULTI_UNITS] DECIMAL(12,4) NULL,
	[NEW_MULTI_UNIT_RETAIL] DECIMAL(12,4) NULL,
	[NEW_MULTI_SELLING_UOM] [nvarchar](4) NULL,
	[STATUS] [nvarchar](1) NULL,
	[TAXABLE_IND] [nvarchar](1) NULL,
	[PROMOTION] DECIMAL(10) NULL,
	[MIX_MATCH_NO] DECIMAL(10) NULL,
	[MIX_MATCH_TYPE] [nvarchar](1) NULL,
	[THRESHOLD_NO] DECIMAL(10) NULL,
	[LAUNCH_DATE] [nvarchar](8) NULL,
	[QTY_KEY_OPTIONS] [nvarchar](6) NULL,
	[MANUAL_PRICE_ENTRY] [nvarchar](6) NULL,
	[DEPOSIT_CODE] [nvarchar](6) NULL,
	[FOOD_STAMP_IND] [nvarchar](1) NULL,
	[WIC_IND] [nvarchar](2) NULL,
	[PROPORTIONAL_TARE_PCT] DECIMAL(12,4) NULL,
	[FIXED_TARE_VALUE] DECIMAL(12,4) NULL,
	[FIXED_TARE_UOM] [nvarchar](4) NULL,
	[REWARD_ELIGIBLE_IND] [nvarchar](1) NULL,
	[ELECT_MTK_CLUBS] [nvarchar](6) NULL,
	[RETURN_POLICY] [nvarchar](6) NULL,
	[STOP_SALE_IND] [nvarchar](1) NULL,
	[RETURNABLE_IND] [nvarchar](1) NULL,
	[REFUNDABLE_IND] [nvarchar](1) NULL,
	[BACK_ORDER_IND] [nvarchar](1) NULL,
	[VAT_CODE] [nvarchar](6) NULL,
	[VAT_RATE] DECIMAL(20,10) NULL,
	[CLASS_VAT_IND] [nvarchar](1) NULL,
	[LINE_ID] DECIMAL NULL,
	[LOAD_TIMESTAMP] [datetime2] NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL,
	[MSG_POS] [nvarchar](38) NULL,
	[PROM_BIN_CODE] [nvarchar](11) NULL,
	[PROM_NAME] [nvarchar](40) NULL
) ON [PRIMARY]
GO


IF OBJECT_ID (N'FEM_POS_PROM_DETAIL_STG', N'U') IS NOT NULL
BEGIN
  DROP TABLE [FEM_POS_PROM_DETAIL_STG] ;
END

CREATE TABLE [dbo].[FEM_POS_PROM_DETAIL_STG](
	[STORE] DECIMAL(10) NULL,
	[PROMOTION] DECIMAL(10) NULL,
	[PROM_TRAN_TYPE] [nvarchar](6) NULL,
	[START_TIME] [datetime2] NULL,
	[END_TIME] [datetime2] NULL,
	[MIX_MATCH_NO] DECIMAL(10) NULL,
	[THRESHOLD_NO] DECIMAL(10) NULL,
	[APPLY_TO] [nvarchar](1) NULL,
	[BUY_TYPE] [nvarchar](1) NULL,
	[BUY_AMT] DECIMAL(20,4) NULL,
	[GET_TYPE] [nvarchar](1) NULL,
	[GET_AMT] DECIMAL(20,4) NULL,
	[SELLING_UOM] [nvarchar](2) NULL,
	[THRESHOLD_AMT] DECIMAL(20,4) NULL,
	[DISCOUNT_AMT] DECIMAL(20,4) NULL,
	[DISCOUNT_TYPE] [nvarchar](1) NULL,
	[LOAD_TIMESTAMP] [datetime2] NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL

) ON [PRIMARY]
GO

IF OBJECT_ID (N'XXFC_MAESTRO_DE_CRS_V', N'U') IS NOT NULL
BEGIN
  DROP TABLE [XXFC_MAESTRO_DE_CRS_V] ;
END

CREATE TABLE [dbo].[XXFC_MAESTRO_DE_CRS_V](
	[ORACLE_CR] [nvarchar](30) NOT NULL,
	[ORACLE_CR_DESC] [nvarchar](100) NULL,
	[ORACLE_CR_SUPERIOR] [nvarchar](30) NULL,
	[ORACLE_CR_TYPE] [nvarchar](1) NOT NULL,
	[ESTADO] [nvarchar](1) NOT NULL,
	[RETEK_CR] DECIMAL NULL,
	[RETEK_ASESOR] DECIMAL NULL,
	[RETEK_ASESOR_NOMBRE] [nvarchar](50) NULL,
	[RETEK_DISTRITO] DECIMAL NULL,
	[RETEK_PLAZA] DECIMAL NULL,
	[RETEK_STATUS] [nvarchar](1) NULL,
	[SURH_CR] DECIMAL(5) NULL,
	[SURH_FLAG] [nvarchar](1) NULL,
	[CR_FLEX_VALUE_ID] DECIMAL(15) NOT NULL,
	[ORACLE_EF] [nvarchar](240) NOT NULL,
	[ORACLE_EF_DESC] [nvarchar](100) NULL,
	[EF_FLEX_VALUE_ID] DECIMAL(15) NOT NULL,
	[ORACLE_CIA] [nvarchar](240) NOT NULL,
	[ORACLE_CIA_DESC] [nvarchar](100) NULL,
	[CIA_FLEX_VALUE_ID] DECIMAL(15) NOT NULL,
	[ID_ESTADO_FINANCIERO] [nvarchar](240) NULL,
	[ID_CENTRO_RESPONSABILIDAD] DECIMAL(15) NOT NULL,
	[ID_COMPANIA] DECIMAL(15) NOT NULL,
	[LEGACY_EF] [nvarchar](2) NULL,
	[LEGACY_CR] [nvarchar](3) NOT NULL
) ON [PRIMARY]
GO
