CREATE TRIGGER PromotionHeaderDeleteTrigger
       ON [dbo].[PROMOTION_HEADER]
AFTER DELETE
AS
BEGIN
   DECLARE @LOAD_BATCH_ID DECIMAL;
   SELECT @LOAD_BATCH_ID = DELETED.LOAD_BATCH_ID
   FROM DELETED

   DECLARE @LOCATION DECIMAL;
   SELECT @LOCATION = DELETED.LOCATION
   FROM DELETED

   DECLARE DeletedCursor CURSOR FOR
   SELECT [LOAD_BATCH_ID], [LOCATION]
   FROM DELETED

   OPEN DeletedCursor
   FETCH NEXT FROM DeletedCursor INTO @LOAD_BATCH_ID, @LOCATION

   WHILE @@FETCH_STATUS = 0 
   BEGIN
      INSERT INTO [dbo].[PROMOTION_HEADER_ARCHIVE]
      ([ARCHIVED_DATE],
	   [LOAD_BATCH_ID],
       [LOCATION]
	   )
      VALUES
      (GETDATE(),
       @LOAD_BATCH_ID,
       @LOCATION)

      -- Next row...
      FETCH NEXT FROM DeletedCursor INTO @LOAD_BATCH_ID, @LOCATION
   END   
END
