DECLARE @BatchID DECIMAL = 190913
DECLARE @Location DECIMAL = 20849
DECLARE @LoadBatchID DECIMAL = 122146421

SELECT *
FROM [dbo].[PRM_PROMOTION_HEADER] h
JOIN [dbo].[PRM_PROMOTION_DATA] d ON h.[LOAD_BATCH_ID] = d.[LOAD_BATCH_ID] and h.[LOCATION] = d.[STORE] and h.[LOAD_WEEK] = d.[LOAD_WEEK]
LEFT OUTER JOIN [dbo].[PRM_PROMOTION_DATA_DETAILS] pd ON pd.PROMOTION = d.PROMOTION and pd.STORE = d.STORE and d.LOAD_BATCH_ID = pd.LOAD_BATCH_ID
JOIN [dbo].[PRM_XXFC_MAESTRO_DE_CRS_V] x ON x.RETEK_CR = d.STORE
WHERE h.[BATCH_ID] = @BatchID and h.[LOCATION] = @Location and h.[LOAD_BATCH_ID] = @LoadBatchID
ORDER BY d.[LOAD_BATCH_ID], d.[STORE], d.[LOAD_TIMESTAMP]

SELECT @@ROWCOUNT
GO

SELECT count(*) FROM [dbo].[PRM_PROMOTION_HEADER] WHERE LOCATION = 924
SELECT count(*) FROM [dbo].[PRM_PROMOTION_DATA] WHERE STORE = 924
SELECT count(*) FROM [dbo].[PRM_PROMOTION_DATA_DETAILS] WHERE STORE = 924
SELECT count(*) FROM [dbo].[PRM_XXFC_MAESTRO_DE_CRS_V] WHERE [RETEK_CR] = 924

