SELECT * FROM [dbo].[PRM_PROMOTION_HEADER]
SELECT * FROM [dbo].[PRM_PROMOTION_DATA]
SELECT * FROM [dbo].[PRM_PROMOTION_DATA_DETAILS]
--SELECT * FROM [dbo].[PRM_POS_RULES_DOC_CFG]
--SELECT * FROM [dbo].[PRM_DOC_STATUS]
SELECT * FROM [dbo].[PRM_XXFC_MAESTRO_DE_CRS_V]

/*
SELECT * FROM [dbo].[PROMOTION_HEADER_ARCHIVE]
SELECT * FROM [dbo].[PROMOTION_DATA_ARCHIVE]
SELECT * FROM [dbo].[PROMOTION_DATA_DETAILS_ARCHIVE]
*/

/*
DELETE FROM [dbo].[PROMOTION_HEADER]
DELETE FROM [dbo].[PROMOTION_DATA]
DELETE FROM [dbo].[PROMOTION_DATA_DETAILS]
DELETE FROM [dbo].[PROMOTION_HEADER_ARCHIVE]
*/

/*
SELECT * FROM [dbo].[POS_PRM_HEAD]
SELECT * FROM [dbo].[FEM_POS_MODS_PRM_STG]
SELECT * FROM [dbo].[FEM_POS_PROM_DETAIL_STG]
SELECT * FROM [dbo].[FEM_POS_LOCATION_STATUS]
*/
