SELECT [LOAD_BATCH_ID]
      ,[LOAD_TIMESTAMP]
      ,[LOAD_WEEK]
      ,[PROMOTION]
      ,[STORE]
      ,[THRESHOLD_NO]
  FROM [dbo].[PRM_PROMOTION_DATA]
  WHERE STORE = 924

SELECT [LOAD_BATCH_ID]
      ,[LOAD_TIMESTAMP]
      ,[LOAD_WEEK]
      ,[PROMOTION]
      ,[STORE]
      ,[THRESHOLD_NO]
  FROM [dbo].[PRM_PROMOTION_DATA_DETAILS]
  WHERE STORE = 924



