DECLARE @BatchID DECIMAL = 182599
DECLARE @Location DECIMAL = 924
DECLARE @LoadBatchID DECIMAL = 122176113

SELECT
	h.[BATCH_ID],
	h.[LOCATION],
	h.[ARCHIVO],
	h.[LOAD_DATE],
	h.[LOAD_WEEK],
	h.[LOAD_BATCH_ID],
	h.[WM_PRM_STATUS],
	h.[WM_TARGET_PRM],
	p.[STORE],
	p.[UPDATE_TYPE],
	p.[START_DATE],
	p.[END_DATE],
	p.[TIME],
	p.[END_TIME],
	p.[TRAN_TYPE],
	p.[ITEM],
	p.[ITEM_NUMBER_TYPE],
	p.[FORMAT_ID],
	p.[PREFIX],
	p.[REF_ITEM],
	p.[REF_ITEM_NUMBER_TYPE],
	p.[REF_FORMAT_ID],
	p.[REF_PREFIX],
	p.[ITEM_SHORT_DESC],
	p.[ITEM_LONG_DESC],
	p.[DEPT],
	p.[CLASS],
	p.[SUBCLASS],
	p.[NEW_PRICE],
	p.[NEW_SELLING_UOM],
	p.[NEW_MULTI_UNITS],
	p.[NEW_MULTI_UNIT_RETAIL],
	p.[NEW_MULTI_SELLING_UOM],
	p.[STATUS],
	p.[TAXABLE_IND],
	p.[PROMOTION],
	p.[MIX_MATCH_NO],
	p.[MIX_MATCH_TYPE],
	p.[THRESHOLD_NO],
	p.[LAUNCH_DATE],
	p.[QTY_KEY_OPTIONS],
	p.[MANUAL_PRICE_ENTRY],
	p.[DEPOSIT_CODE],
	p.[FOOD_STAMP_IND],
	p.[WIC_IND],
	p.[PROPORTIONAL_TARE_PCT],
	p.[FIXED_TARE_VALUE],
	p.[FIXED_TARE_UOM],
	p.[REWARD_ELIGIBLE_IND],
	p.[ELECT_MTK_CLUBS],
	p.[RETURN_POLICY],
	p.[STOP_SALE_IND],
	p.[RETURNABLE_IND],
	p.[REFUNDABLE_IND],
	p.[BACK_ORDER_IND],
	p.[VAT_CODE],
	p.[VAT_RATE],
	p.[CLASS_VAT_IND],
	p.[LINE_ID],
	p.[LOAD_TIMESTAMP],
	p.[MSG_POS],
	p.[PROM_BIN_CODE],
	p.[PROM_NAME],
	d.[PROM_TRAN_TYPE],
	d.[START_TIME],
	d.[APPLY_TO],
	d.[BUY_TYPE],
	d.[BUY_AMT],
	d.[GET_TYPE],
	d.[GET_AMT],
	d.[SELLING_UOM],
	d.[THRESHOLD_AMT],
	d.[DISCOUNT_AMT],
	d.[DISCOUNT_TYPE]
FROM [dbo].[PRM_PROMOTION_HEADER] h
JOIN [dbo].[PRM_PROMOTION_DATA] p ON p.[STORE] = h.LOCATION and p.[LOAD_BATCH_ID] = h.[LOAD_BATCH_ID]
JOIN [dbo].[PRM_PROMOTION_DATA_DETAILS] d ON p.[STORE] = d.[STORE] and p.[LOAD_BATCH_ID] = d.[LOAD_BATCH_ID] and p.[PROMOTION] = d.[PROMOTION] and p.[THRESHOLD_NO] = d.[THRESHOLD_NO] and p.[LOAD_WEEK] = d.[LOAD_WEEK]
-- JOIN [dbo].[PRM_XXFC_MAESTRO_DE_CRS_V] x ON x.RETEK_CR = d.STORE
WHERE h.[LOCATION] = @Location and h.[LOAD_BATCH_ID] = @LoadBatchId and h.[LOAD_BATCH_ID] = @LoadBatchID
ORDER BY d.[LOAD_BATCH_ID], d.[STORE], d.[LOAD_TIMESTAMP]

SELECT [ORACLE_CR]
      ,[ORACLE_CR_DESC]
      ,[ORACLE_CR_SUPERIOR]
      ,[ORACLE_CR_TYPE]
      ,[ESTADO]
      ,[RETEK_CR]
      ,[RETEK_ASESOR]
      ,[RETEK_ASESOR_NOMBRE]
      ,[RETEK_DISTRITO]
      ,[RETEK_PLAZA]
      ,[RETEK_STATUS]
      ,[SURH_CR]
      ,[SURH_FLAG]
      ,[CR_FLEX_VALUE_ID]
      ,[ORACLE_EF]
      ,[ORACLE_EF_DESC]
      ,[EF_FLEX_VALUE_ID]
      ,[ORACLE_CIA]
      ,[ORACLE_CIA_DESC]
      ,[CIA_FLEX_VALUE_ID]
      ,[ID_ESTADO_FINANCIERO]
      ,[ID_CENTRO_RESPONSABILIDAD]
      ,[ID_COMPANIA]
      ,[LEGACY_EF]
      ,[LEGACY_CR]
FROM [dbo].[PRM_XXFC_MAESTRO_DE_CRS_V]
WHERE [RETEK_CR] = 924
