/*
IF OBJECT_ID (N'CO_PRM_DAT_HDR', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DAT_HDR] ;
END

IF OBJECT_ID (N'CO_PRM_DAT', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DAT] ;
END

IF OBJECT_ID (N'CO_PRM_DAT_DTL', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DAT_DTL] ;
END

-- IF OBJECT_ID (N'CO_ERDD_MCRS', N'U') IS NOT NULL
-- BEGIN
--   DROP TABLE [CO_ERDD_MCRS] ;
-- END

IF OBJECT_ID (N'CO_PRM_STR_DCM_CFG', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_STR_DCM_CFG] ;
END

IF OBJECT_ID (N'CO_PRM_DCM_STS', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DCM_STS] ;
END

IF OBJECT_ID (N'CO_PRM_PRCS', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_PRCS] ;
END

IF OBJECT_ID (N'CO_PRM_HEADD', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_HEADD] ;
END

IF OBJECT_ID (N'CO_PRM_HEADP', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_HEADP] ;
END

IF OBJECT_ID (N'CO_PRM_CONFIGD', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_CONFIGD] ;
END
*/

CREATE TABLE [dbo].[CO_PRM_DAT_HDR](
	[BATCH_ID] DECIMAL NULL,
	[LOCATION] DECIMAL NULL,
	[ARCHIVO] [nvarchar](255) NULL,
	[LOAD_DATE] [datetime2] NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL,
	[WM_PRM_STATUS] [nvarchar](1) NULL,
	[WM_TARGET_PRM] [nvarchar](255) NULL,
	[CLOUD_PRM_STATUS] [nvarchar](1) NULL,
	[CLOUD_TARGET_PRM] [nvarchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_PRM_DAT](
	[STORE] DECIMAL(10) NULL,
	[UPDATE_TYPE] DECIMAL NULL,
	[START_DATE] [datetime2] NULL,
	[END_DATE] [datetime2] NULL,
	[TIME] [datetime2] NULL,
	[END_TIME] [datetime2] NULL,
	[TRAN_TYPE] DECIMAL(2) NULL,
	[ITEM] [nvarchar](25) NULL,
	[ITEM_NUMBER_TYPE] [nvarchar](6) NULL,
	[FORMAT_ID] [nvarchar](1) NULL,
	[PREFIX] DECIMAL(2) NULL,
	[REF_ITEM] [nvarchar](25) NULL,
	[REF_ITEM_NUMBER_TYPE] [nvarchar](6) NULL,
	[REF_FORMAT_ID] [nvarchar](1) NULL,
	[REF_PREFIX] DECIMAL(2) NULL,
	[ITEM_SHORT_DESC] [nvarchar](20) NULL,
	[ITEM_LONG_DESC] [nvarchar](100) NULL,
	[DEPT] DECIMAL(4) NULL,
	[CLASS] DECIMAL(4) NULL,
	[SUBCLASS] DECIMAL(4) NULL,
	[NEW_PRICE] DECIMAL(20,4) NULL,
	[NEW_SELLING_UOM] [nvarchar](4) NULL,
	[NEW_MULTI_UNITS] DECIMAL(12,4) NULL,
	[NEW_MULTI_UNIT_RETAIL] DECIMAL(12,4) NULL,
	[NEW_MULTI_SELLING_UOM] [nvarchar](4) NULL,
	[STATUS] [nvarchar](1) NULL,
	[TAXABLE_IND] [nvarchar](1) NULL,
	[PROMOTION] DECIMAL(10) NULL,
	[MIX_MATCH_NO] DECIMAL(10) NULL,
	[MIX_MATCH_TYPE] [nvarchar](1) NULL,
	[THRESHOLD_NO] DECIMAL(10) NULL,
	[LAUNCH_DATE] [nvarchar](8) NULL,
	[QTY_KEY_OPTIONS] [nvarchar](6) NULL,
	[MANUAL_PRICE_ENTRY] [nvarchar](6) NULL,
	[DEPOSIT_CODE] [nvarchar](6) NULL,
	[FOOD_STAMP_IND] [nvarchar](1) NULL,
	[WIC_IND] [nvarchar](2) NULL,
	[PROPORTIONAL_TARE_PCT] DECIMAL(12,4) NULL,
	[FIXED_TARE_VALUE] DECIMAL(12,4) NULL,
	[FIXED_TARE_UOM] [nvarchar](4) NULL,
	[REWARD_ELIGIBLE_IND] [nvarchar](1) NULL,
	[ELECT_MTK_CLUBS] [nvarchar](6) NULL,
	[RETURN_POLICY] [nvarchar](6) NULL,
	[STOP_SALE_IND] [nvarchar](1) NULL,
	[RETURNABLE_IND] [nvarchar](1) NULL,
	[REFUNDABLE_IND] [nvarchar](1) NULL,
	[BACK_ORDER_IND] [nvarchar](1) NULL,
	[VAT_CODE] [nvarchar](6) NULL,
	[VAT_RATE] DECIMAL(20,10) NULL,
	[CLASS_VAT_IND] [nvarchar](1) NULL,
	[LINE_ID] DECIMAL NULL,
	[LOAD_TIMESTAMP] [datetime2] NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL,
	[MSG_POS] [nvarchar](38) NULL,
	[PROM_BIN_CODE] [nvarchar](11) NULL,
	[PROM_NAME] [nvarchar](40) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_PRM_DAT_DTL](
	[STORE] DECIMAL(10) NULL,
	[PROMOTION] DECIMAL(10) NULL,
	[PROM_TRAN_TYPE] [nvarchar](6) NULL,
	[START_TIME] [datetime2] NULL,
	[END_TIME] [datetime2] NULL,
	[MIX_MATCH_NO] DECIMAL(10) NULL,
	[THRESHOLD_NO] DECIMAL(10) NULL,
	[APPLY_TO] [nvarchar](1) NULL,
	[BUY_TYPE] [nvarchar](1) NULL,
	[BUY_AMT] DECIMAL(20,4) NULL,
	[GET_TYPE] [nvarchar](1) NULL,
	[GET_AMT] DECIMAL(20,4) NULL,
	[SELLING_UOM] [nvarchar](2) NULL,
	[THRESHOLD_AMT] DECIMAL(20,4) NULL,
	[DISCOUNT_AMT] DECIMAL(20,4) NULL,
	[DISCOUNT_TYPE] [nvarchar](1) NULL,
	[LOAD_TIMESTAMP] [datetime2] NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_ERDD_MCRS](
	[ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[ORACLE_CR] [nvarchar](30) NULL,
	[ORACLE_CR_DESC] [nvarchar](100) NULL,
	[ORACLE_CR_SUPERIOR] [nvarchar](30) NULL,
	[ORACLE_CR_TYPE] [nvarchar](1) NULL,
	[ESTADO] [nvarchar](1) NULL,
	[RETEK_CR] DECIMAL NULL,
	[RETEK_ASESOR] DECIMAL NULL,
	[RETEK_ASESOR_NOMBRE] [nvarchar](50) NULL,
	[RETEK_DISTRITO] DECIMAL NULL,
	[RETEK_PLAZA] DECIMAL NULL,
	[RETEK_STATUS] [nvarchar](1) NULL,
	[SURH_CR] DECIMAL(5) NULL,
	[SURH_FLAG] [nvarchar](1) NULL,
	[CR_FLEX_VALUE_ID] DECIMAL(15) NULL,
	[ORACLE_EF] [nvarchar](240) NULL,
	[ORACLE_EF_DESC] [nvarchar](100) NULL,
	[EF_FLEX_VALUE_ID] DECIMAL(15) NULL,
	[ORACLE_CIA] [nvarchar](240) NULL,
	[ORACLE_CIA_DESC] [nvarchar](100) NULL,
	[CIA_FLEX_VALUE_ID] DECIMAL(15) NULL,
	[ID_ESTADO_FINANCIERO] [nvarchar](240) NULL,
	[ID_CENTRO_RESPONSABILIDAD] DECIMAL(15) NULL,
	[ID_COMPANIA] DECIMAL(15) NULL,
	[LEGACY_EF] [nvarchar](2) NULL,
	[LEGACY_CR] [nvarchar](3) NULL
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[CO_PRM_STR_DCM_CFG](
	[ID] [int] IDENTITY(1,1) PRIMARY KEY,
	[DOC_TYPE] nvarchar(32) NULL,
	[DEPARTMENT] nvarchar(32) NULL,
	[STORE] nvarchar(32) NULL,
	[MIGRATED] nvarchar(32) NULL,
	[DIGITAL] nvarchar(32) NULL,
	[FUNCTIONAL_GROUP] nvarchar(32) NULL,
	[LAST_UPDATED_BY] nvarchar(32) NULL,
	[LAST_UPDATE_DATE] [datetime2] NULL,
	[CREATED_BY] nvarchar(32) NULL,
	[CREATED_DATE] [datetime2] NULL,
	[VERSION] DECIMAL NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_PRM_DCM_STS](
	[CREATED_DATE] [datetime2] NOT NULL,
	[RUN_IDENTIFIER] [nvarchar](48),
	[UNIQUE_IDENTIFIER] [nvarchar](48) NOT NULL,
	[PROCESSING_STATUS] [nvarchar](1),
	[DOCUMENT_PROCESSING_START_TIME] [datetime2] NULL,
	[DOCUMENT_PROCESSING_END_TIME] [datetime2] NULL,
	[BATCH_ID] DECIMAL NULL,
	[LOCATION] DECIMAL NULL,
	[STORE] DECIMAL NULL,
	[LOAD_WEEK] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL,
	[DETAILS] nvarchar(max) NULL,
	[RETRIES] DECIMAL NULL,
	[COPY_START_TIME] [datetime2] NULL,
	[COPY_END_TIME] [datetime2] NULL,
	[TRANSFORMATION_START_TIME] [datetime2] NULL,
	[TRANSFORMATION_END_TIME] [datetime2] NULL,
	[CLOUD_PRM_STATUS] [nvarchar](1) NULL,
	[CR_PLAZA] [nvarchar](30) NULL,
	[CR_TIENDA] [nvarchar](30) NULL,
	[SOURCE] [nvarchar](10) NULL,
	[PV_DOC_NAME] [nvarchar](256) NULL,
	[PV_DOC_TYPE] [nvarchar](10) NULL,
	[PV_STATUS] [nvarchar](1) NULL,
	[PV_EVENT_DATE] [nvarchar](19) NULL,
	[NUMBER_OF_RECORDS] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CO_PRM_DCM_STS] ADD PRIMARY KEY CLUSTERED
(
    [UNIQUE_IDENTIFIER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CO_PRM_DCM_STS] ADD  CONSTRAINT [CO_PRMS_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

CREATE TABLE [dbo].[CO_PRM_PRCS](
	[CREATED_DATE] [datetime2] CONSTRAINT CO_PRMS_RUNNING DEFAULT GETDATE(),
	[RUN_IDENTIFIER] [nvarchar](48),
	[UNIQUE_IDENTIFIER] [nvarchar](48),
	[BATCH_ID] DECIMAL NULL,
	[LOCATION] DECIMAL NULL,
	[LOAD_BATCH_ID] DECIMAL NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_PRM_HEADP](
	[ID_PRM_HDR_OX] [int] IDENTITY(1,1) PRIMARY KEY,
	[CY_PRM] [nvarchar](5) NULL,
	[NM_ORGN] [nvarchar](100) NULL,
	[ID_DEPT] [nvarchar](50) NULL,
	[ID_STR] [nvarchar](50) NULL,
	[NMB_PRM] [int] NULL,
	[ID_SCH] [nvarchar](50) NULL,
	[SND_PRM] [nvarchar](50) NULL,
	[DST_PRM] [nvarchar](50) NULL,
	[ID_RCVR] [nvarchar](50) NULL,
	[DT_SCH] [datetime2] NULL,
	[STS_PRM] [bit] NULL,
	[FL] [bit] NULL,
	[LCNT] [int] NULL,
	[ID_OPR_CRT] [uniqueidentifier] NULL,
	[TM_CRT] [datetime2] NULL,
	[ID_OPR_MDY] [uniqueidentifier] NULL,
	[TM_MDY] [datetime2] NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_PRM_HEADD](
	[ID_PRM_DTL_OX] [int] IDENTITY(1,1) PRIMARY KEY,
	[ID_PRM_HDR_OX] [int] NULL,
	[NMB_PRM] [int] NULL,
	[FO_PRM] [nvarchar](20) NULL,
	[CTGY_ITM] [nvarchar](10) NULL,
	[TYP_PRM] [nvarchar](10) NULL,
	[SRT_DT_PRM] [datetime2] NULL,
	[FNS_DT_PRM] [datetime2] NULL,
	[SKU] [nvarchar](20) NULL,
	[CTGY_PRM] [nvarchar](50) NULL,
	[TYP_SPR] [nvarchar](10) NULL,
	[QTY_REQT_PRM] DECIMAL(10,3) NULL,
	[DSC] DECIMAL(10,3) NULL,
	[TYP_DSC] [nvarchar](10) NULL,
	[OPT_PRM] [int] NULL,
	[DSCP_ITM] [nvarchar](255) NULL,
	[SUB_CTGY_ITM] [nvarchar](50) NULL,
	[SGMT_ITM] [nvarchar](50) NULL,
	[SUB_SGMT_ITM] [nvarchar](50) NULL,
	[DRN_CD] [nvarchar](20) NULL,
	[GP_PRM] DECIMAL(10,3) NULL,
	[PRCT_PRM] DECIMAL(5,2) NULL,
	[FS_OPTN_PRN]  [nvarchar](50) NULL,
	[SND_PRM]  [nvarchar](50) NULL,
	[TYP_PRM_AD] [nvarchar](10) NULL,
	[CD_PRM] [nvarchar](50) NULL,
	[MSG_PRM] [nvarchar](255) NULL,
	[FL] BIT NULL,
	[LCNT] INT NULL,
	[ID_OPR_CRT] UNIQUEIDENTIFIER NULL,
	[TM_CRT] [datetime2] NULL,
	[ID_OPR_MDY] UNIQUEIDENTIFIER NULL,
	[TM_MDY] [datetime2] NULL,
	CONSTRAINT ID_PRM_HDR_OX_FK FOREIGN KEY ([ID_PRM_HDR_OX]) REFERENCES CO_PRM_HEADP([ID_PRM_HDR_OX])
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CO_PRM_CONFIGD](
	[CREATED_DATE] [datetime2] CONSTRAINT PRMS_RUN DEFAULT GETDATE(),
	[RUN_IDENTIFIER] [nvarchar](48),
	[IsRunning] [nvarchar](1) NULL,
	[ReturnValue] [int] NULL,
	[Description] [nvarchar](256) NULL
) ON [PRIMARY]
GO
