
IF OBJECT_ID (N'CO_PRM_DAT_HDR', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DAT_HDR] ;
END

IF OBJECT_ID (N'CO_PRM_DAT', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DAT] ;
END

IF OBJECT_ID (N'CO_PRM_DAT_DTL', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DAT_DTL] ;
END

-- IF OBJECT_ID (N'CO_ERDD_MCRS', N'U') IS NOT NULL
-- BEGIN
--   DROP TABLE [CO_ERDD_MCRS] ;
-- END

IF OBJECT_ID (N'CO_PRM_STR_DCM_CFG', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_STR_DCM_CFG] ;
END

IF OBJECT_ID (N'CO_PRM_DCM_STS', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_DCM_STS] ;
END

IF OBJECT_ID (N'CO_PRM_PRCS', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_PRCS] ;
END

IF OBJECT_ID (N'CO_PRM_HEADD', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_HEADD] ;
END

IF OBJECT_ID (N'CO_PRM_HEADP', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_HEADP] ;
END

IF OBJECT_ID (N'CO_PRM_CONFIGD', N'U') IS NOT NULL
BEGIN
  DROP TABLE [CO_PRM_CONFIGD] ;
END
