name: Create Cloud Tables and Stored Procedures

on:
  workflow_dispatch:
    # Trigger on push to main branch; adjust as needed

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'PROD' || github.ref == 'refs/heads/staging' && 'QA' || 'DEV' }}
  CLOUD_SQL_CREATE_TABLE_SQL_PATH: 'src/DataFactory/Scripts/SQL/SQLAzureDevProd/Create_Promotion_SQL_Tables.sql'
  CLOUD_SQL_CREATE_SPROC_SQL_PATH: 'src/DataFactory/Scripts/SQL/SQLAzureDevProd/SProcs'

jobs:
  create-tables:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure SQL Managed Instance - Create Tables
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_CLOUD', env.ENVIRONMENT)] }}
        path: ${{ env.CLOUD_SQL_CREATE_TABLE_SQL_PATH }}

  create-sprocs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure SQL Managed Instance - Create Stored Procedure - CreateGetPromomotionDataXmlSproc
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_CLOUD', env.ENVIRONMENT)] }}
        path: ${{ env.CLOUD_SQL_CREATE_SPROC_SQL_PATH }}/CreateGetPromomotionDataXmlSproc.sql

    - name: Azure SQL Managed Instance - Create Stored Procedure - CreateGetPromotionDataSproc
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_CLOUD', env.ENVIRONMENT)] }}
        path: ${{ env.CLOUD_SQL_CREATE_SPROC_SQL_PATH }}/CreateGetPromotionDataSproc.sql

    - name: Azure SQL Managed Instance - Create Stored Procedure - CreateGetPromotionStatusDataSproc
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_CLOUD', env.ENVIRONMENT)] }}
        path: ${{ env.CLOUD_SQL_CREATE_SPROC_SQL_PATH }}/CreateGetPromotionStatusDataSproc.sql

    - name: Azure SQL Managed Instance - Create Stored Procedure - CreateInsertPromotionDetailsIntoPromotionDetailsTable
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_CLOUD', env.ENVIRONMENT)] }}
        path: ${{ env.CLOUD_SQL_CREATE_SPROC_SQL_PATH }}/CreateInsertPromotionDetailsIntoPromotionDetailsTable.sql
