name: Deploy to Azure Function App

on:
  push:
    branches:
      - develop
      - staging
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  PACKAGE_PATH: "src/AzureFunctions/OxxoPromotionFunctionApp"
  PROJECT_FILE: "OxxoPromotionFunctionApp.csproj"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./publish"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ${{ env.PACKAGE_PATH }}/${{ env.PROJECT_FILE }}

      - name: Build project
        run: dotnet build ${{ env.PACKAGE_PATH }}/${{ env.PROJECT_FILE }} --configuration Release

      - name: Publish project
        run: dotnet publish ${{ env.PACKAGE_PATH }}/${{ env.PROJECT_FILE }} --configuration Release --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.FUNCTION_APP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'qa' || 'development' }}
