name: Populate Cloud DB Mastero Table Data

on:
  workflow_dispatch:
    # Trigger on push to main branch; adjust as needed

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'PROD' || github.ref == 'refs/heads/staging' && 'QA' || 'DEV' }}
  CLOUD_SQL_POPULATE_SQL_PATH: "src/DataFactory/Scripts/SQL/SQLAzureDevProd"

jobs:
  populate-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure SQL Managed Instance - Populate Mastero Tables
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_CLOUD', env.ENVIRONMENT)] }}
          path: ${{ env.CLOUD_SQL_POPULATE_SQL_PATH }}/PopulateMaestroTable.sql
