name: Populate Mock DB Data 

on:
  workflow_dispatch:
    # Trigger on push to main branch; adjust as needed

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'PROD' || github.ref == 'refs/heads/staging' && 'QA' || 'DEV' }}
  MOCK_SQL_POPULATE_SQL_PATH: "src/DataFactory/Scripts/SQL/OracleOnPremMock"
  
jobs:
  populate-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set connection string
        run: echo "AZURE_SQL_CONNECTION_STRING_MOCK=${{ secrets[format('{0}_AZURE_SQL_CONNECTION_STRING_MOCK', env.ENVIRONMENT)] }}" >> $GITHUB_ENV

      - name: Azure SQL Managed Instance - Populate SQL Tables
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ env.AZURE_SQL_CONNECTION_STRING_MOCK }}
          path: ${{ env.MOCK_SQL_POPULATE_SQL_PATH }}/Populate_Oracle_Tables.sql
